loan/urls.py
from django.urls import path
from . import views
from .views import (
    LoanHomeView,
    CreateLoanView,
    LoanDetailsView,
    ListLoanView,
    LoanCollectionCreateView,
    LoanCollectionDetailsView,
    LoanCollectionUpdateView,
)
import loan

app_name = "loan"

urlpatterns = [
    path("", LoanHomeView.as_view(), name="loan-home"),
    path("/create", CreateLoanView.as_view(), name="loan-create"),
    path(
        "/<int:loan_id>",
        LoanDetailsView.as_view(),
        name="loan-details",
    ),
    path("/list", ListLoanView.as_view(), name="loan-list"),
    path(
        "/loan-collection/create",
        LoanCollectionCreateView.as_view(),
        name="loan-collection-create",
    ),
    path(
        "collection/<int:loan_collection_id>",
        LoanCollectionDetailsView.as_view(),
        name="collection-details",
    ),
    path(
        "collection/<int:loan_collection_id>/update",
        LoanCollectionUpdateView.as_view(),
        name="collection-update",
    ),
]

loanManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

# Views
from dashboard import views

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("dashboard.urls")),
        path("members", include("members.urls")),
        path("loan", include("loan.urls")),
        path("deposite", include("deposite.urls")),
    ]
    # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

members/urls.py
from django.urls import path
from . import views
from .views import (
    CreateMembersView,
    MemberHomeView,
    ReadMemberView,
    UpdateMemberView,
    DeleteMemberView,
    MemberSearchView,
)

app_name = "members"

urlpatterns = [
    # dashboard
    path("", MemberHomeView.as_view(), name="members-home"),
    path("/create", CreateMembersView.as_view(), name="members-create"),
    path(
        "/<str:member_name>/<int:member_no>",
        ReadMemberView.as_view(),
        name="members-details",
    ),
    path(
        "/update/<str:member_name>/<int:member_no>",
        UpdateMemberView.as_view(),
        name="members-update",
    ),
    path(
        "/<str:member_name>/<int:member_no>/delete",
        DeleteMemberView.as_view(),
        name="members-delete",
    ),
    path(
        "/search",
        MemberSearchView.as_view(),
        name="members-search",
    ),
]

members/models.py
from django.db import models
from django.core.validators import MaxValueValidator, RegexValidator

# Create your models here.


class Memberarea(models.Model):
    area_id = models.IntegerField(primary_key=True, default=1999, editable=False)
    area_name = models.CharField(max_length=200)

    def save(self, *args, **kwargs):
        if not Memberarea.objects.count():
            self.area_id = 2000
        else:
            self.area_id = Memberarea.objects.last().area_id + 1
        super(Memberarea, self).save(*args, **kwargs)

    def __str__(self):
        return self.area_name


class Memberprofile(models.Model):
    member_no = models.IntegerField(primary_key=True, default=0, editable=False)
    member_name = models.CharField(max_length=500)
    phone_regex = RegexValidator(regex="(^([+]{1}[8]{2}|0088)?(01){1}[3-9]{1}\d{8})$")
    member_phone_number = models.CharField(
        validators=[phone_regex], max_length=14, blank=True
    )
    member_nid = models.PositiveBigIntegerField(max_length=17)

    member_image = models.ImageField(
        default="member_icon.png", upload_to="members-profile-pictures"
    )
    member_mother_name = models.CharField(max_length=500)
    member_father_name = models.CharField(max_length=500)
    member_spouse_name = models.CharField(max_length=500)
    nominee = models.CharField(max_length=500)
    present_address = models.CharField(max_length=500)
    present_city = models.CharField(max_length=50, null=True, blank=True)
    present_village = models.CharField(max_length=50, null=True, blank=True)
    present_union = models.CharField(max_length=50, null=True, blank=True)
    present_word = models.CharField(max_length=50, null=True, blank=True)
    present_thana = models.CharField(max_length=50, null=True, blank=True)
    present_district = models.CharField(max_length=50, null=True, blank=True)
    permanent_address = models.CharField(max_length=500)
    permanent_city = models.CharField(max_length=50, null=True, blank=True)
    permanent_village = models.CharField(max_length=50, null=True, blank=True)
    permanent_union = models.CharField(max_length=50, null=True, blank=True)
    permanent_word = models.CharField(max_length=50, null=True, blank=True)
    permanent_thana = models.CharField(max_length=50, null=True, blank=True)
    permanent_district = models.CharField(max_length=50, null=True, blank=True)
    member_area = models.ForeignKey(Memberarea, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        if not Memberprofile.objects.count():
            self.member_no = 1000
        else:
            self.member_no = Memberprofile.objects.last().member_no + 1
        super(Memberprofile, self).save(*args, **kwargs)

    def __str__(self):
        return self.member_name

members/forms.py
from django import forms

from .models import Memberprofile, Memberarea


class MemberProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Memberprofile
        fields = "__all__"

members/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.views.generic.base import TemplateView
from .models import Memberprofile, Memberarea
from dashboard.models import Adminprofile
from .forms import MemberProfileUpdateForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView,
)


class MemberHomeView(LoginRequiredMixin, ListView):
    model = Memberprofile
    # template_name = "members/members-home.html"
    template_name = "members/a.html"
    context_object_name = "memberProfiles"


class CreateMembersView(LoginRequiredMixin, CreateView):
    model = Memberprofile
    fields = "__all__"
    success_url = "/members"

    def form_valid(self, form):

        return super().form_valid(form)


class ReadMemberView(LoginRequiredMixin, DetailView):
    model = Memberprofile

    def get_object(self, *args, **kwargs):
        m_id_url = self.kwargs.get("member_no")
        member_no = Memberprofile.objects.get(member_no=m_id_url)
        return member_no

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        member_no = self.get_object()
        context["member"] = Memberprofile.objects.get(member_no=member_no.member_no)
        return context


class UpdateMemberView(UpdateView, LoginRequiredMixin):
    model = Memberprofile
    fields = "__all__"
    success_url = "/members"
    template_name = "members/memberprofile_update.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_object(self, *args, **kwargs):
        m_id_url = self.kwargs.get("member_no")
        member_no = Memberprofile.objects.get(member_no=m_id_url)
        return member_no

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        member_no = self.get_object()
        context["member"] = Memberprofile.objects.get(member_no=member_no.member_no)
        return context


class DeleteMemberView(DeleteView, LoginRequiredMixin):
    model = Memberprofile

    success_url = "/members"

    def get_object(self, queryset=None):
        return Memberprofile.objects.get(member_no=self.kwargs.get("member_no"))

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class MemberSearchView(ListView, LoginRequiredMixin):
    model = Memberprofile

    def post(self, request):
        searched = request.POST.get("member_no_from_searchbar")
        searched_id = int(searched)

        try:
            result = Memberprofile.objects.get(member_no=searched_id)
        except Memberprofile.DoesNotExist:
            result = None

        if result:
            context = {
                "member": get_object_or_404(Memberprofile, member_no=searched_id)
            }

            return render(request, "members/members_search.html", context)
        else:
            context = {"no_result": True}
            return render(request, "members/members_search.html", context)

members/templates/members/a.html
{% extends "dashboard/base.html" %}

<!------ Include the above in your HEAD tag ---------->
{% load static %}
{% block bootstrapClass %}
<link rel="stylesheet" type="text/css" href="{% static 'members/members-css/members-create.css' %}">
 {% endblock %}   



{% block content %}



{% include 'members/members-base.html' %}

<h5 style="color: white;">Member Home</h5>

<p style="color: white; margin-left: 45%;">Search by Member id</p>
<form  class="navbar-form navbar-left" action="{% url 'members:members-search' %}" method="POST">
    {% csrf_token %}
    <input style="margin-left:20%;" type="search" name="member_no_from_searchbar"  class="form-control col-lg-8" placeholder="Search"><button type="submit" style="margin-left:48%;" class="btn btn-outline-primary mt-4 mb-4">Search</button>
  </form>


<div class="content-section">
    <section  id="team" class="pb-5">
        <div class="container">
            <h5 class="section-title h1">Members</h5>
            <div class="row">
                <!-- Team member -->
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <div class="image-flip" >
                        <div class="mainflip flip-0">
                            <div class="frontside">
                                {% for profile in memberProfiles %}
                                <div class="card">
                                    
                                    <div class="card-body text-center">
                                        <p><img class=" img-fluid" src="{{profile.member_image.url}}" alt="card image"></p>
                                        <h4 class="card-title"> <a href="{% url 'members:members-details' profile.member_name profile.member_no %}">{{profile.member_name}}</a></h4>
                                        <p class="card-text"><span style="font-weight: bold;">Phone:</span> {{profile.member_phone_number}}</p>
                                        <p class="card-text"><span style="font-weight: bold;">Address:</span> {{profile.present_address}}</p>
                                        
                                    </div>                         
                                </div>
                                {% endfor %}
                            </div>                         
                        </div>                    
                    </div>              
                </div>            
            </div>       
        </div>
   

        <div class="backside">
            <div class="card">
                <div class="card-body text-center mt-4">
                    <h4 class="card-title">Sunlimetech</h4>
                    <p class="card-text">This is basic card with image on top, title, description and button.This is basic card with image on top, title, description and button.This is basic card with image on top, title, description and button.</p>
                    <ul class="list-inline">
                        <li class="list-inline-item">
                            <a class="social-icon text-xs-center" target="_blank" href="https://www.fiverr.com/share/qb8D02">
                                <i class="fa fa-facebook"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="social-icon text-xs-center" target="_blank" href="https://www.fiverr.com/share/qb8D02">
                                <i class="fa fa-twitter"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="social-icon text-xs-center" target="_blank" href="https://www.fiverr.com/share/qb8D02">
                                <i class="fa fa-skype"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="social-icon text-xs-center" target="_blank" href="https://www.fiverr.com/share/qb8D02">
                                <i class="fa fa-google"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
       
    </section>
    
        </div> 
     
        

 <!-- <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css"> -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% endblock %}

members/templates/members/memberprofile_confirm_delete.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block title %}<title>Member Delete</title>{% endblock %}
     
 {% load crispy_forms_tags %}

{% block content %}
{% include 'members/members-base.html' %}
    <div class="content-section">
        <form method="POST">
            {%csrf_token%}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Delete Post
                </legend>
                <h2>Are you sure you want to delete the post "{{object.member_name}}"</h2>
               
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">yes, delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'members:members-details' object.member_name object.member_no %}" >Cancel</a>
            </div>
        </form>

{% endblock content %}

members/templates/members/memberprofile_detail.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block title %}<title>Member Details</title>{% endblock %}
     
 {% load crispy_forms_tags %}
 



{% block content %}
{% include 'members/members-base.html' %}
<button   class="btn btn-outline-info mb-4"><a href="{% url 'members:members-update' member.member_name member.member_no %}">Update {{member.member_name}}</a></button>
<a class="btn btn-outline-danger mb-4 " href="{% url 'members:members-delete' member.member_name member.member_no %}">Delete</a>
  <article class="media content-section">
    <img style=" height: 65px;
          width: 65px;
          margin-right: 16px;
          border-radius: 20px;" class="rounded-circle article-img" src="{{ member.member_image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="#">{{ member.member_name }}</a>
        <a class="mr-2" href="#">{{ member.permanent_village }}</a>
        </div>
  </article>
{% endblock content %}

members/templates/members/memberprofile_form.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block title %}<title>Yay! A New Member</title>{% endblock %}

{% block bootstrapClass %}
<link rel="stylesheet" type="text/css" href="{% static 'members/members-css/members-create.css' %}">
 {% endblock %}    
{% load crispy_forms_tags %}


{% block content %}
{% include 'members/members-base.html' %}


<div class="content-section">
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset style="text-align: center; display: flex; flex-wrap: wrap;
        padding-left: 0; flex: 0 0 33.333333%; gap: 30px;" class="form-group">
            <legend class="border-bottom mb-4">Create Members</legend>
            {{form.media}}
            {{form|crispy}}
            
        </fieldset>
        <div class="form-group">
            <button class="btn btn-info mt-3 create-button" type="submit">Create</button>
        </div>
    </form>
 
</div>



{% endblock content %}

members/templates/members/memberprofile_update.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block title %}<title>Update Member</title>{% endblock %}

{% block bootstrapClass %}
<link rel="stylesheet" type="text/css" href="{% static 'members/members-css/members-create.css' %}">
 {% endblock %}    
{% load crispy_forms_tags %}


{% block content %}
{% include 'members/members-base.html' %}


<div class="content-section">
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset style="text-align: center; display: flex; flex-wrap: wrap;
        padding-left: 0; flex: 0 0 33.333333%; gap: 30px;" class="form-group">
            <legend class="border-bottom mb-4">Update Members</legend>
            {{form.media}}
            {{form|crispy}}
            
        </fieldset>
        <div class="form-group">
            <button class="btn btn-info mt-3 create-button" type="submit">Update</button>
        </div>
    </form>
 
</div>



{% endblock content %}

members/templates/members/members-base.html
<div 
style=  "display: flex;
        align-items: center;
        justify-content: center; 
        gap: 12px;
        margin-top: 100px;
        margin-bottom: 50px;"
>
    <button style="width: 150px;"  class="btn btn-outline-info"><a href="{% url 'members:members-home' %}">Members</a></button>
    <button style="width: 150px;"   class="btn btn-outline-info"><a href="{% url 'members:members-create' %}">Create Members</a></button>
</div>

members/templates/members/members-home.html
{% extends "dashboard/base.html" %}

{% block content %}

{% include 'members/members-base.html' %}

<h1 style="color: white;">Member Home</h1>

<p style="color: white; margin-left: 45%;">Search by Member id</p>
<form  class="navbar-form navbar-left" action="{% url 'members:members-search' %}" method="POST">
    {% csrf_token %}
    <input style="margin-left:20%;" type="search" name="member_no_from_searchbar"  class="form-control col-lg-8" placeholder="Search"><button type="submit" style="margin-left:48%;" class="btn btn-outline-primary mt-4 mb-4">Search</button>
  </form>


{% for profile in memberProfiles %}
        <article class="media content-section">

          <img style=" height: 65px;
          width: 65px;
          margin-right: 16px;
          border-radius: 20px;" class="rounded-cirle article-img" src="{{profile.member_image.url}}" alt="">
          <div class="media-body">
            <div class="article-metadata">
              <a href="{% url 'members:members-details' profile.member_name profile.member_no %}" class="mr-2 "  >{{ profile.member_name }}</a>
              <a class="mr-2 " >{{ profile.member_area }}</a>
              <a class="mr-2 " >{{ profile.member_phone_number }}</a>
            </div>
    
            <p class="article-content">{{ profile.present_address}}</p>
          </div>
        </article>

    {% endfor %} 
   
{% endblock %}

members/templates/members/members_search.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block title %}<title>Search Result</title>{% endblock %}
     
 {% load crispy_forms_tags %}
 



{% block content %}
{% include 'members/members-base.html' %}

{% if member %}
<button   class="btn btn-outline-info mb-4"><a href="{% url 'members:members-update' member.member_name member.member_no %}">Update {{member.member_name}}</a></button>
<a class="btn btn-outline-danger mb-4 " href="{% url 'members:members-delete' member.member_name member.member_no %}">Delete</a>
  <article class="media content-section">
    <img style=" height: 65px;
          width: 65px;
          margin-right: 16px;
          border-radius: 20px;" class="rounded-circle article-img" src="{{ member.member_image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="#">{{ member.member_name }}</a>
        <a class="mr-2" href="#">{{ member.permanent_village }}</a>
        </div>
  </article>

  {% endif %}

  {% if no_result %}

  <p style="color: white; margin-left: 45%;">Search by Member id</p>
<form  class="navbar-form navbar-left" action="{% url 'members:members-search' %}" method="POST">
    {% csrf_token %}
    <input style="margin-left:20%;" type="search" name="member_no_from_searchbar"  class="form-control col-lg-8" placeholder="Search"><button type="submit" style="margin-left:48%;" class="btn btn-outline-primary mt-4 mb-4">Search</button>
  </form>


  <h5 style="color: white;" >No member with such id. Search again</h5>
  {% endif %}
{% endblock content %}