loan/urls.py
from django.urls import path
from . import views
from .views import (
    LoanHomeView,
    CreateLoanView,
    LoanDetailsView,
    ListLoanView,
    LoanCollectionCreateView,
    LoanCollectionDetailsView,
    LoanCollectionUpdateView,
)
import loan

app_name = "loan"

urlpatterns = [
    path("", LoanHomeView.as_view(), name="loan-home"),
    path("/create", CreateLoanView.as_view(), name="loan-create"),
    path(
        "/<int:loan_id>",
        LoanDetailsView.as_view(),
        name="loan-details",
    ),
    path("/list", ListLoanView.as_view(), name="loan-list"),
    path(
        "/loan-collection/create",
        LoanCollectionCreateView.as_view(),
        name="loan-collection-create",
    ),
    path(
        "collection/<int:loan_collection_id>",
        LoanCollectionDetailsView.as_view(),
        name="collection-details",
    ),
    path(
        "collection/<int:loan_collection_id>/update",
        LoanCollectionUpdateView.as_view(),
        name="collection-update",
    ),
]

loanManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

# Views
from dashboard import views

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("dashboard.urls")),
        path("members", include("members.urls")),
        path("loan", include("loan.urls")),
        path("deposite", include("deposite.urls")),
    ]
    # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

members/urls.py
from django.urls import path
from . import views
from .views import (
    CreateMembersView,
    MemberHomeView,
    ReadMemberView,
    UpdateMemberView,
    DeleteMemberView,
    MemberSearchView,
)

app_name = "members"

urlpatterns = [
    # dashboard
    path("", MemberHomeView.as_view(), name="members-home"),
    path("/create", CreateMembersView.as_view(), name="members-create"),
    path(
        "/<str:member_name>/<int:member_no>",
        ReadMemberView.as_view(),
        name="members-details",
    ),
    path(
        "/update/<str:member_name>/<int:member_no>",
        UpdateMemberView.as_view(),
        name="members-update",
    ),
    path(
        "/<str:member_name>/<int:member_no>/delete",
        DeleteMemberView.as_view(),
        name="members-delete",
    ),
    path(
        "/search",
        MemberSearchView.as_view(),
        name="members-search",
    ),
]

loan/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date
from djmoney.models.fields import MoneyField

# models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from members.models import Memberprofile, Memberarea
from dashboard.models import Adminprofile


class Loan(models.Model):

    LOAN_TYPE_CHOICES = (
        ("MONTHLY", "Monthly"),
        ("DAILY", "Daily"),
    )

    loan_id = models.IntegerField(primary_key=True, default=0, editable=False)
    member_no = models.ForeignKey(Memberprofile, on_delete=CASCADE)
    loan_area = models.ForeignKey(Memberarea, on_delete=CASCADE)
    loan_approved_by = models.ForeignKey(Adminprofile, on_delete=CASCADE)
    loan_passed_date = models.DateTimeField(default=timezone.now)
    loan_amount = MoneyField(max_digits=19, decimal_places=4, default_currency="TAKA")

    loan_period = models.DateTimeField(default=timezone.now)
    Loan_type = models.CharField(
        max_length=9, choices=LOAN_TYPE_CHOICES, default="MONTHLY"
    )

    def save(self, *args, **kwargs):
        if not Loan.objects.count():
            self.loan_id = 3000
        else:
            self.loan_id = Loan.objects.last().loan_id + 1

        self.loan_area = self.member_no.member_area

        super(Loan, self).save(*args, **kwargs)


class Loancollentionsheet(models.Model):
    loan_collection_id = models.IntegerField(
        primary_key=True, default=0, editable=False
    )
    loan_id = models.ForeignKey(
        Loan, on_delete=CASCADE, related_name="loan_collection_loan_id"
    )

    member = models.CharField(max_length=500)
    # member_id = models.IntegerField(default=0, max_length=10000)
    loan_deposite_amount = MoneyField(
        max_digits=19, decimal_places=4, default_currency="TAKA"
    )
    loan_deposite_withdrawal = MoneyField(
        max_digits=19, decimal_places=4, default_currency="TAKA"
    )
    loan_deposite_balance = MoneyField(
        max_digits=19, decimal_places=4, default_currency="TAKA"
    )

    loan_collection_installment_amount = MoneyField(
        max_digits=19, decimal_places=4, default_currency="TAKA"
    )
    loan_total_collection = MoneyField(
        max_digits=19, decimal_places=4, default_currency="TAKA"
    )

    loan_payable_installment_amount = MoneyField(
        max_digits=19, decimal_places=4, default_currency="TAKA"
    )

    loan_number_of_installments = models.IntegerField(max_length=100)

    def withdraw_loan_deposite(self):

        if self.loan_deposite_balance < self.loan_deposite_withdrawal:
            return "Not possible"
        new_balance = self.loan_deposite_balance - self.loan_deposite_withdrawal
        self.loan_deposite_balance = new_balance
        return {
            "new_balance": self.loan_deposite_balance,
            "withdrawal_amount": self.loan_deposite_withdrawal,
        }

    def add_loan_deposite(self):
        new_balance = self.loan_deposite_balance + self.loan_deposite_amount
        self.loan_deposite_balance = new_balance
        return self.loan_deposite_balance

    def loan_withdrawal_func(self):

        if self.loan_deposite_withdrawal > self.loan_deposite_amount:
            raise ValueError

        new_balance = self.loan_deposite_amount - self.loan_deposite_withdrawal
        self.loan_deposite_withdrawal = new_balance
        return self.loan_deposite_withdrawal

    def add_loan_collection_installment_amount(self):
        self.loan_number_of_installments += 1
        self.loan_payable_installment_amount = (
            self.loan_payable_installment_amount
            - self.loan_collection_installment_amount
        )
        self.loan_total_collection += self.loan_collection_installment_amount

    def check_loan_collection_possibility(self):
        if (
            self.loan_collection_installment_amount
            > self.loan_payable_installment_amount
        ):
            return False

    def save(self, *args, **kwargs):
        if not Loancollentionsheet.objects.count():
            self.loan_collection_id = 4000
        else:
            self.loan_collection_id = (
                Loancollentionsheet.objects.last().loan_collection_id + 1
            )

        self.member = self.loan_id.member_no.member_name

        self.loan_total_collection = self.loan_collection_installment_amount
        self.loan_deposite_balance = self.loan_deposite_amount
        self.loan_payable_installment_amount = (
            self.loan_id.loan_amount - self.loan_collection_installment_amount
        )
        super(Loancollentionsheet, self).save(*args, **kwargs)

loan/forms.py
from django import forms
from django.db import models
from django.db.models import fields

from members.models import Memberprofile, Memberarea
from .models import Loan, Loancollentionsheet


class LoanForm(forms.ModelForm):
    class Meta:
        model = Loan
        exclude = ["loan_area"]


class LoanCollectionForm(forms.ModelForm):
    class Meta:
        model = Loancollentionsheet
        exclude = [
            "member",
            "loan_total_collection",
            "loan_deposite_balance",
            "loan_payable_installment_amount",
        ]


class LoanCollectionUpdateForm(forms.ModelForm):
    class Meta:
        model = Loancollentionsheet
        exclude = [
            "loan_id",
            "member",
            "loan_total_collection",
            "loan_deposite_balance",
            "loan_payable_installment_amount",
            "loan_number_of_installments",
        ]

loan/views.py
import loan
from typing import Collection
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.views.generic.base import TemplateView
from members.models import Memberprofile, Memberarea
from dashboard.models import Adminprofile
from .models import Loan, Loancollentionsheet
from djmoney.money import Money

from .forms import LoanForm, LoanCollectionForm, LoanCollectionUpdateForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView,
)


# Create your views here.
class LoanHomeView(LoginRequiredMixin, ListView):
    model = Loancollentionsheet
    template_name = "loan/loan-home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["collections"] = Loancollentionsheet.objects.all()
        return context


class CreateLoanView(LoginRequiredMixin, CreateView):
    model = Loan
    template_name = "loan/loan-create.html"
    form_class = LoanForm
    success_url = "/loan"

    def form_valid(self, form):
        # form.instance.loan_approved_by = self.request.user
        return super().form_valid(form)


class LoanDetailsView(LoginRequiredMixin, DetailView):
    model = Loan
    template_name = "loan/loan-details.html"

    def get_object(self, *args, **kwargs):
        id_from_url = self.kwargs.get("loan_id")
        loan = Loan.objects.get(loan_id=id_from_url)
        return loan

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        loan = self.get_object()
        context["loan"] = Loan.objects.get(loan_id=loan.loan_id)
        return context


class ListLoanView(LoginRequiredMixin, ListView):
    model = Loan
    template_name = "loan/loan-list.html"
    queryset = Loan.objects.all()
    context_object_name = "loans"


class LoanCollectionCreateView(LoginRequiredMixin, CreateView):
    model = Loancollentionsheet
    template_name = "loan/loan-collection-create.html"
    form_class = LoanCollectionForm
    success_url = "/loan"

    def form_valid(self, form):
        # form.instance.loan_approved_by = self.request.user
        return super().form_valid(form)


class LoanCollectionDetailsView(LoginRequiredMixin, DetailView):
    model = Loancollentionsheet
    template_name = "loan/loan-collection-details.html"

    def get_object(self, *args, **kwargs):
        id_from_url = self.kwargs.get("loan_collection_id")
        collection = Loancollentionsheet.objects.get(loan_collection_id=id_from_url)
        return collection

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        collection = self.get_object()
        context["collection"] = Loancollentionsheet.objects.get(
            loan_collection_id=collection.loan_collection_id
        )
        return context


class LoanCollectionUpdateView(LoginRequiredMixin, UpdateView):
    model = Loancollentionsheet
    template_name = "loan/loan-collection-update.html"
    form_class = LoanCollectionUpdateForm
    success_url = "/loan"

    def get_object(self, *args, **kwargs):
        id_from_url = self.kwargs.get("loan_collection_id")
        collection = Loancollentionsheet.objects.get(loan_collection_id=id_from_url)
        return collection

    def form_valid(self, form):
        # (
        #     deposite_amount,
        #     withdrawal_amount,
        #     collection_amount,
        # ) = self.post()  # list unpacking

        data = form.cleaned_data
        deposite_amount = data["loan_deposite_amount"]
        withdrawal_amount = data["loan_deposite_withdrawal"]
        collection_amount = data["loan_collection_installment_amount"]

        collection = self.get_object()
        new_update = Loancollentionsheet.objects.get(
            loan_collection_id=collection.loan_collection_id
        )
        if deposite_amount > Money(0, "BDT"):
            new_update.add_loan_deposite()

        if withdrawal_amount > Money(0, "BDT"):
            new_update.loan_withdrawal_func()

        if collection_amount:
            if new_update.check_loan_collection_possibility():
                new_update.add_loan_collection_installment_amount()
        new_update.save()

        return super().form_valid(form)

loan/templates/loan/loan-base.html
<div 
style=  "display: flex;
        align-items: center;
        justify-content: center; 
        gap: 12px;
        margin-top: 100px;
        margin-bottom: 50px;"
>
    <button style="width: 150px;"  
    class="btn btn-outline-info">
    <a href="{% url 'loan:loan-home' %}">loan</a>
    </button>



    <button style="width: 150px;"   
    class="btn btn-outline-info">
    <a href="{% url 'loan:loan-create' %}">Create loan</a>
    </button>
    
    <button style="width: 150px;"   
    class="btn btn-outline-info">
    <a href="{% url 'loan:loan-list' %}">loan list</a>
    </button>

    <button style="width: 150px;"   
    class="btn btn-outline-info">
    <a href="{% url 'loan:loan-collection-create' %}">Create Collection</a>
    </button>

</div>

loan/templates/loan/loan-collection-create.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block title %}<title>New Loan Collection</title>{% endblock %}

{% block bootstrapClass %}
<link rel="stylesheet" type="text/css" href="{% static 'loan/loan-css/loan-create.css' %}">
 {% endblock %}    
{% load crispy_forms_tags %}


{% block content %}
{% include 'loan/loan-base.html' %}


<div class="content-section">
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset style="text-align: center; display: flex; flex-wrap: wrap;
        padding-left: 0; flex: 0 0 33.333333%; gap: 30px;" class="form-group">
            <legend class="border-bottom mb-4">Create loan Collection</legend>
            {{form.media}}
            {{form|crispy}}
            
        </fieldset>
        <div class="form-group">
            <button class="btn btn-info mt-3 create-button" type="submit">Create</button>
        </div>
    </form>
 
</div>



{% endblock content %}

loan/templates/loan/loan-collection-details.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block title %}<title>Member Details</title>{% endblock %}
     
 {% load crispy_forms_tags %}
 



{% block content %}
{% include 'loan/loan-base.html' %}

<button   class="btn btn-outline-info mb-4">
  <a href="{% url 'loan:collection-update' collection.loan_collection_id %}">
  Update 
  </a>
  </button>

  <article class="media content-section">
    <img style=" height: 65px;
          width: 65px;
          margin-right: 16px;
          border-radius: 20px;" class="rounded-circle article-img"
         src="{{ collection.loan_id.member_no.member_image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <p>collection_id: {{ collection.loan_collection_id}}</p>
        <p>loan_id: {{ collection.loan_id.loan_id}}</p>
        <p>Member Name: {{ collection.member}}</p>
        <p>member_id: {{ collection.loan_id.member_no.member_no}}</p>
        <p>Loan Amount: {{ collection.loan_id.loan_amount}}</p>
        <p>Total Collection: {{collection.loan_total_collection}}</p>
        <p>Amount left: {{collection.loan_payable_installment_amount }}</p>
        <p>Number of installments: {{collection.loan_number_of_installments}}</p>
        <p>Deposite Balance: {{ collection.loan_deposite_balance}}</p>
        </div>
  </article>
{% endblock content %}

loan/templates/loan/loan-collection-update.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block title %}<title>New Loan Collection</title>{% endblock %}

{% block bootstrapClass %}
<link rel="stylesheet" type="text/css" href="{% static 'loan/loan-css/loan-create.css' %}">
 {% endblock %}    
{% load crispy_forms_tags %}


{% block content %}
{% include 'loan/loan-base.html' %}


<div style="border: 1.5px solid #007bff;" class="content-section">
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset style="text-align: center; display: flex; flex-wrap: wrap;
        padding-left: 0; flex: 0 0 33.333333%; gap: 30px;" class="form-group">
            <legend class="border-bottom mb-4">Update loan Collection</legend>
            
            {{form|crispy}}
            
        </fieldset>
        <div class="form-group">
            <button class="btn btn-info mt-3 create-button" type="submit">Update</button>
        </div>
    </form>
 
</div>



{% endblock content %}

loan/templates/loan/loan-create.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block title %}<title>New Loan</title>{% endblock %}

{% block bootstrapClass %}
<link rel="stylesheet" type="text/css" href="{% static 'loan/loan-css/loan-create.css' %}">
 {% endblock %}    
{% load crispy_forms_tags %}


{% block content %}
{% include 'loan/loan-base.html' %}


<div class="content-section">
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset style="text-align: center; display: flex; flex-wrap: wrap;
        padding-left: 0; flex: 0 0 33.333333%; gap: 30px;" class="form-group">
            <legend class="border-bottom mb-4">Create loan</legend>
            {{form.media}}
            {{form|crispy}}
            
        </fieldset>
        <div class="form-group">
            <button class="btn btn-info mt-3 create-button" type="submit">Create</button>
        </div>
    </form>
 
</div>



{% endblock content %}

loan/templates/loan/loan-details.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block title %}<title>Member Details</title>{% endblock %}
     
 {% load crispy_forms_tags %}
 



{% block content %}
{% include 'loan/loan-base.html' %}

  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <p> ID: {{loan.loan_id}}</p>
        <p>NAME: {{loan.member_no.member_name}}</p>
        <p>LOAN AREA: {{loan.loan_area}}</p>
        <p>AMOUNT: {{loan.loan_amount}}</p>
        </div>
  </article>
{% endblock content %}

loan/templates/loan/loan-home.html
{% extends "dashboard/base.html" %}

{% load static %}
{% block bootstrapClass %}
<link rel="stylesheet" type="text/css" href="{% static 'members/members-css/members-create.css' %}">
 {% endblock %}   



{% block content %}

{% include 'loan/loan-base.html' %}

<p style="color: white; margin-left: 45%;">Search by loan id</p>
<form  class="navbar-form navbar-left" action="{% url 'members:members-search' %}" method="POST">
    {% csrf_token %}
    <input style="margin-left:20%;" type="search" name="member_no_from_searchbar"  class="form-control col-lg-8" placeholder="Search"><button type="submit" style="margin-left:48%;" class="btn btn-outline-primary mt-4 mb-4">Search</button>
  </form>

  <h3 style="color: white; margin-left:35%;">Loan Collection Dashboard </h3>



{% for collection in collections %}
<div  style="color: white; text-align: center;">
<p> <a href="{% url 'loan:collection-details' collection.loan_collection_id %}">collection_id: {{ collection.loan_collection_id}}</a> </p>
<p>loan_id: {{ collection.loan_id.loan_id}}</p>
<p>Member Name: {{ collection.member}}</p>
<p>member_id: {{ collection.loan_id.member_no.member_no}}</p>
<p>Loan Amount: {{ collection.loan_id.loan_amount}}</p>
<p>Total Collection: {{collection.loan_total_collection}}</p>
<p>Amount left: {{collection.loan_payable_installment_amount }}</p>
<p>Number of installments: {{collection.loan_number_of_installments}}</p>
<p>Deposite Balance: {{ collection.loan_deposite_balance}}</p>
==========================
</div>
{% endfor %}





{% endblock %}

loan/templates/loan/loan-list.html
{% extends "dashboard/base.html" %}

{% load static %}
{% block bootstrapClass %}
<link rel="stylesheet" type="text/css" href="{% static 'members/members-css/members-create.css' %}">
 {% endblock %}   



{% block content %}

{% include 'loan/loan-base.html' %}

{% for loan in loans %}

<div style="color: white;">
<p > <a href="{% url 'loan:loan-details' loan.loan_id %}"> ID: {{loan.loan_id}}</a></p>
<p>NAME: {{loan.member_no.member_name}}</p>
<p>LOAN AREA: {{loan.loan_area}}</p>
<p>AMOUNT: {{loan.loan_amount}}</p>

===============================================

</div>

{% endfor %}
{% endblock %}