dashboard/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "dashboard"

urlpatterns = [
    # dashboard
    path("", views.home, name="home"),
    path("signup/", views.signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="dashboard/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="dashboard/logout.html"),
        name="logout",
    ),
    path("profile-update", views.profileUpdateView, name="admin-profile-update"),
]

loan/urls.py
from django.urls import path
from . import views
from .views import (
    LoanHomeView,
    CreateLoanView,
    LoanDetailsView,
    ListLoanView,
    LoanCollectionCreateView,
    LoanCollectionDetailsView,
    LoanCollectionUpdateView,
)
import loan

app_name = "loan"

urlpatterns = [
    path("", LoanHomeView.as_view(), name="loan-home"),
    path("/create", CreateLoanView.as_view(), name="loan-create"),
    path(
        "/<int:loan_id>",
        LoanDetailsView.as_view(),
        name="loan-details",
    ),
    path("/list", ListLoanView.as_view(), name="loan-list"),
    path(
        "/loan-collection/create",
        LoanCollectionCreateView.as_view(),
        name="loan-collection-create",
    ),
    path(
        "collection/<int:loan_collection_id>",
        LoanCollectionDetailsView.as_view(),
        name="collection-details",
    ),
    path(
        "collection/<int:loan_collection_id>/update",
        LoanCollectionUpdateView.as_view(),
        name="collection-update",
    ),
]

loanManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

# Views
from dashboard import views

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("dashboard.urls")),
        path("members", include("members.urls")),
        path("loan", include("loan.urls")),
        path("deposite", include("deposite.urls")),
    ]
    # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

members/urls.py
from django.urls import path
from . import views
from .views import (
    CreateMembersView,
    MemberHomeView,
    ReadMemberView,
    UpdateMemberView,
    DeleteMemberView,
    MemberSearchView,
)

app_name = "members"

urlpatterns = [
    # dashboard
    path("", MemberHomeView.as_view(), name="members-home"),
    path("/create", CreateMembersView.as_view(), name="members-create"),
    path(
        "/<str:member_name>/<int:member_no>",
        ReadMemberView.as_view(),
        name="members-details",
    ),
    path(
        "/update/<str:member_name>/<int:member_no>",
        UpdateMemberView.as_view(),
        name="members-update",
    ),
    path(
        "/<str:member_name>/<int:member_no>/delete",
        DeleteMemberView.as_view(),
        name="members-delete",
    ),
    path(
        "/search",
        MemberSearchView.as_view(),
        name="members-search",
    ),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.


class Adminprofile(models.Model):
    user = models.OneToOneField(
        User, related_name="adminprofile", on_delete=models.CASCADE
    )
    image = models.ImageField(
        default="admin-icon.png", upload_to="admin-profile-pictures"
    )

    def __str__(self):
        return f"{self.user.username}'s Profile"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

dashboard/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Adminprofile


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email"]


class AdminProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Adminprofile
        fields = ["image"]

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from .models import Adminprofile
from django.contrib import messages
from .forms import UserRegistrationForm, UserUpdateForm, AdminProfileUpdateForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse_lazy

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Account created for {username}")
            return redirect("dashboard:home")

    else:
        form = UserRegistrationForm()
    return render(request, "dashboard/signup.html", {"form": form})


@login_required
def home(request):

    context = {"profile_info": Adminprofile.objects.all()}
    return render(request, "dashboard/home.html", context)


class Home(ListView):
    template_name = "dashboard/home.html"
    model = Adminprofile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        loggedInProfile = Adminprofile.objects.get(user=self.request.user)

        context["loggedInProfile"] = loggedInProfile

        return context


def profileUpdateView(request):
    if request.method == "POST":

        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = AdminProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.adminprofile
        )

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"successfully updated")
            return redirect("dashboard:admin-profile-update")

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = AdminProfileUpdateForm(instance=request.user.adminprofile)
    context = {"u_form": u_form, "p_form": p_form}
    return render(request, "dashboard/update-profile.html", context)

dashboard/templates/dashboard/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/dashboard-css/base.css' %}">
    
    {% block bootstrapClass %}  {% endblock %}
    {% block title %}<title>Loan Management</title>{% endblock %}
</head> 
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark navbar-bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'dashboard:home' %}">CommunityBanking</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
          
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'members:members-home' %}">Members</a>
                {% endif %}
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'loan:loan-home' %}">Loan</a>
                <a class="nav-item nav-link" href="">Deposite</a>
                <a class="nav-item nav-link" href="{% url 'dashboard:logout' %}">logout</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'dashboard:login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'dashboard:signup' %}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>
    
  
    <main role="main" class="container">


          {% block content %}{% endblock %}

      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

dashboard/templates/dashboard/home.html
{% extends "dashboard/base.html" %}

{% block content %}

<div class="container" style="text-align: center;"> 
<h5 style="color: white;">Welcome to your profile {{user.username}}</h5>
<img class="rounded-circle account-img" src="{{ user.adminprofile.image.url }}">

<button style="display: block; margin: auto;" class="btn btn-outline-info"><a href="{% url 'dashboard:admin-profile-update' %}">Update Profile</a></button>
</div>

{% endblock %}

dashboard/templates/dashboard/login.html
{% extends "dashboard/base.html" %}
{%load static %}
{% block title %}<title>Login</title>{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {%csrf_token%}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Log In
                </legend>

                {{form | crispy}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Log In</button>
            </div>
        </form>

        <div class="border-top pt-3">
            <small class="text-muted">Need an account?<a href="{%url 'dashboard:signup' %}">Register Here</a></small>
        </div>
    </div>
{% endblock content %}

dashboard/templates/dashboard/logout.html
{% extends "dashboard/base.html" %}
{%load static %}

{% block title %}<title>Logout</title>{% endblock %}
{% load crispy_forms_tags %}

{% block content %}

        <h2 style="color:white">You have been logged out</h2>
        <div class="border-top pt-3">
            <small style="color: white;" class="text-muted">Log back in?<a href="{%url 'dashboard:login' %}">log in</a></small>
            <small  style='color: white;' class="text-muted">Need an account?<a href="{%url 'dashboard:signup' %}">Register Here</a></small>
        </div>
    
{% endblock content %}

dashboard/templates/dashboard/signup.html
{% extends "dashboard/base.html" %}
{%load static %}
{% block title %}<title>signup</title>{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {%csrf_token%}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    JOIN TODAY
                </legend>

                {{form | crispy}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign up</button>
            </div>
        </form>

        <div class="border-top pt-3">
            <small class="text-muted">Already have Account? Login here <a href="{% url 'dashboard:login' %}">Login</a></small>
        </div>
    </div>
{% endblock content %}

dashboard/templates/dashboard/update-profile.html
{% extends "dashboard/base.html" %}
{% block title %}<title>{{user.username}}</title>{% endblock %}

{%load static %}

{% block bootstrapClass %}

 {% endblock %}


{% load crispy_forms_tags %}

{% block content %} 
    
<div class="profile-wrap">
    <div class="media content-section profile-head">
      <img class="rounded-circle account-img" src="{{ user.adminprofile.image.url }}">
      <div class="media-body">
        <h2 class="account-heading">{{user.username}}</h2>
        <p class="text-secondary">{{user.email}}</p>
      </div>
    </div>
    <!-- FORM  -->
    <div class="content-section">
      <form method="POST", enctype="multipart/form-data">
          {%csrf_token%}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">
                  Profile Info
              </legend>

              {{u_form | crispy}}
              {{p_form | crispy}}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Update</button>
          </div>
      </form>
      </div>
{% endblock content %}